### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by js-kyle** [puzrin/mincer#244]
Hi there,

Thanks for the merge & publish of the Lodash version bump yesterday. I noticed this project has now been listed as unmaintained - I would be interested in taking over ownership, mainly to keep up security updates such as the ones I have been contributing to.

Let me know if you would be interested in that.

Thanks

**Comment by puzrin** [comment]
As far as i understand, you are author of [connect-assets](https://github.com/js-kyle/connect-assets), and it's the main active consumer of this package now.

I'm ok to transfer you repo ownership & publishing permission. I would ask only about 2 things:

- reflect ownership change in changelog (in next release)
- if you decide to refresh supported engine versions, do it in 3.0.0, to guarantee stability of versions, published by us.

Is it ok?

@ixti?

**Comment by js-kyle** [comment]
@puzrin Yes -  both of those points make sense to me

**Comment by ixti** [comment]
@puzrin totally fine with me!

**Comment by puzrin** [comment]
Done

@js-kyle, confirm transfer request.

**Comment by js-kyle** [comment]
@puzrin Thanks, that is done. I will make the changelog update as you requested in the next day or so when I get some time
